#!/usr/bin/env python3
"""Export the FastAPI schema to the versioned OpenAPI YAML snapshot."""

import argparse
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
BACKEND = ROOT / "backend"
OUTPUT = ROOT / "docs" / "openapi.yaml"
sys.path.insert(0, str(BACKEND))

from app.main import app  # noqa: E402

HEADER = "# Generated by scripts/export_openapi.py. Do not edit manually.\n"


def rendered_schema() -> str:
    return HEADER + yaml.safe_dump(
        app.openapi(),
        allow_unicode=True,
        sort_keys=False,
        width=100,
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if docs/openapi.yaml is not synchronized",
    )
    args = parser.parse_args()
    rendered = rendered_schema()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != rendered:
            print(
                "docs/openapi.yaml is stale; run scripts/export_openapi.py",
                file=sys.stderr,
            )
            return 1
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(rendered)
    print(f"Wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
