from datetime import datetime
from typing import Protocol
from uuid import UUID

from .entities import (
    Category,
    Event,
    EventDraft,
    EveningPlan,
    Identity,
    Preferences,
    Reaction,
    ReactionCounts,
    User,
)


class UserRepositoryPort(Protocol):
    async def get(self, user_id: UUID) -> User | None: ...
    async def upsert_identity(self, identity: Identity, now: datetime) -> User: ...
    async def complete_onboarding(self, user_id: UUID, city: str) -> User: ...


class PreferencesRepositoryPort(Protocol):
    async def get(self, user_id: UUID) -> Preferences | None: ...
    async def save(
        self, user_id: UUID, preferences: Preferences, now: datetime
    ) -> None: ...


class EventRepositoryPort(Protocol):
    async def get(self, event_id: UUID) -> Event | None: ...
    async def available(
        self, city: str, provider: str, now: datetime, *, inclusive: bool = True
    ) -> list[Event]: ...
    async def has_available(self, city: str, provider: str, now: datetime) -> bool: ...
    async def favorites(self, user_id: UUID, provider: str) -> list[Event]: ...
    async def upsert(self, event: EventDraft) -> None: ...
    async def deactivate_missing(
        self, city: str | None, provider: str, external_ids: tuple[str, ...]
    ) -> None: ...


class ReactionRepositoryPort(Protocol):
    async def history(self, user_id: UUID) -> list[Reaction]: ...
    async def saved_ids(self, user_id: UUID) -> set[UUID]: ...
    async def save(self, user_id: UUID, event_id: UUID, reaction: str) -> None: ...
    async def remove(self, user_id: UUID, event_id: UUID) -> bool: ...
    async def popularity(
        self, user_id: UUID, event_ids: tuple[UUID, ...]
    ) -> dict[UUID, ReactionCounts]: ...


class EveningRepositoryPort(Protocol):
    async def add(self, plan: EveningPlan) -> None: ...
    async def get(self, plan_id: UUID, user_id: UUID) -> EveningPlan | None: ...
    async def saved(self, user_id: UUID) -> list[EveningPlan]: ...
    async def save(
        self, plan_id: UUID, user_id: UUID, now: datetime
    ) -> EveningPlan | None: ...


class UnitOfWorkPort(Protocol):
    users: UserRepositoryPort
    preferences: PreferencesRepositoryPort
    events: EventRepositoryPort
    reactions: ReactionRepositoryPort
    evenings: EveningRepositoryPort

    async def __aenter__(self) -> "UnitOfWorkPort": ...
    async def __aexit__(self, exc_type, exc, traceback) -> None: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
    async def ping(self) -> None: ...


class EventProviderPort(Protocol):
    async def categories(self) -> list[Category]: ...
    async def events(self, city: str) -> list[EventDraft]: ...


class MaxVerifierPort(Protocol):
    def verify(self, raw: str) -> Identity: ...


class TokenPort(Protocol):
    def issue(self, user_id: UUID) -> str: ...
    def verify(self, token: str) -> UUID: ...


class ClockPort(Protocol):
    def now(self) -> datetime: ...
